# Generated by Django 3.1.5 on 2021-02-02 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0003_auto_20210130_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['created_at']},
        ),
    ]
